import os
from PIL import Image, ImageDraw, ImageFont
from datetime import datetime, date

def generate_schedule_image_card(schedule_entries, event_date_str: str, output_path: str) -> str:
    """
    Renders a high-resolution, beautiful schedule summary image card.
    Saves to output_path and returns the absolute filepath.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Canvas dimensions
    width = 1000
    card_margin = 40
    header_height = 160
    entry_height = 140
    footer_height = 80
    
    num_entries = len(schedule_entries) if schedule_entries else 1
    total_height = header_height + (num_entries * (entry_height + 20)) + footer_height + 40

    # Colors
    bg_color = (248, 249, 250)         # #F8F9FA
    primary_color = (79, 70, 229)       # #4F46E5 Indigo
    accent_color = (238, 242, 255)      # #EEF2FF
    text_dark = (30, 41, 59)           # #1E293B
    text_muted = (100, 116, 139)       # #64748B
    border_color = (226, 232, 240)     # #E2E8F0
    card_bg = (255, 255, 255)          # #FFFFFF
    time_badge_bg = (224, 231, 255)    # #E0E7FF

    img = Image.new("RGB", (width, total_height), bg_color)
    draw = ImageDraw.Draw(img)

    # Font setup with fallbacks
    try:
        title_font = ImageFont.truetype("arial.ttf", 36)
        subtitle_font = ImageFont.truetype("arial.ttf", 22)
        time_font = ImageFont.truetype("arialbd.ttf", 20)
        activity_font = ImageFont.truetype("arialbd.ttf", 22)
        detail_font = ImageFont.truetype("arial.ttf", 18)
        footer_font = ImageFont.truetype("arial.ttf", 16)
    except IOError:
        title_font = ImageFont.load_default()
        subtitle_font = ImageFont.load_default()
        time_font = ImageFont.load_default()
        activity_font = ImageFont.load_default()
        detail_font = ImageFont.load_default()
        footer_font = ImageFont.load_default()

    # Draw Header Banner
    draw.rectangle([(0, 0), (width, header_height)], fill=primary_color)
    draw.text((card_margin, 35), "VIKAS SIR - DAILY SCHEDULE DIGEST", fill=(255, 255, 255), font=title_font)
    draw.text((card_margin, 95), f"📅 Date: {event_date_str}", fill=(224, 231, 255), font=subtitle_font)

    # Draw Content
    y_cursor = header_height + 30

    if not schedule_entries:
        # Draw No Schedule Card
        card_rect = [(card_margin, y_cursor), (width - card_margin, y_cursor + 120)]
        draw.rounded_rectangle(card_rect, radius=12, fill=card_bg, outline=border_color, width=2)
        draw.text((card_margin + 30, y_cursor + 45), "☀️ No events scheduled for today.", fill=text_muted, font=activity_font)
        y_cursor += 150
    else:
        for idx, entry in enumerate(schedule_entries, 1):
            card_top = y_cursor
            card_bottom = y_cursor + entry_height
            card_rect = [(card_margin, card_top), (width - card_margin, card_bottom)]

            # Card background shadow / box
            draw.rounded_rectangle(card_rect, radius=14, fill=card_bg, outline=border_color, width=2)

            # Left accent strip
            draw.rounded_rectangle([(card_margin, card_top), (card_margin + 10, card_bottom)], radius=4, fill=primary_color)

            # Time Badge
            time_str = entry.time or "TBD"
            draw.rounded_rectangle([(card_margin + 30, card_top + 20), (card_margin + 240, card_top + 55)], radius=8, fill=time_badge_bg)
            draw.text((card_margin + 42, card_top + 26), f"⏰ {time_str}", fill=primary_color, font=time_font)

            # Activity Title
            activity_text = f"{idx}. {entry.activity}"
            if entry.remark:
                activity_text += f" ({entry.remark})"
            draw.text((card_margin + 260, card_top + 25), activity_text, fill=text_dark, font=activity_font)

            # Details: Location & Responsible Person
            loc_text = f"📍 Location: {entry.location or 'N/A'}"
            resp_text = f"👤 Responsible: {entry.responsible_person or 'N/A'}"
            draw.text((card_margin + 30, card_top + 75), loc_text, fill=text_muted, font=detail_font)
            draw.text((card_margin + 450, card_top + 75), resp_text, fill=text_muted, font=detail_font)

            if entry.google_location:
                draw.text((card_margin + 30, card_top + 105), f"🔗 Map: {entry.google_location[:60]}...", fill=primary_color, font=detail_font)

            y_cursor += entry_height + 20

    # Draw Footer
    draw.line([(card_margin, y_cursor), (width - card_margin, y_cursor)], fill=border_color, width=1)
    footer_text = f"Generated by Vikas Sir Schedule Management System • {datetime.now().strftime('%d %b %Y, %I:%M %p')}"
    draw.text((card_margin, y_cursor + 20), footer_text, fill=text_muted, font=footer_font)

    img.save(output_path)
    print(f"[ImageGenerator] Schedule image saved to: {output_path}")
    return output_path
